pluginManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }

        maven {
            name = "Terraformers"
            url = "https://maven.terraformersmc.com/"
        }

        mavenCentral()
    }
}

rootProject.name = "Rune_Finder_GoatDardo"